name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/mn2sts ]

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  tag-repo:
    runs-on: ubuntu-latest
    needs: prepare
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

      - name: Parse mn2sts version
        env:
          mn2sts_TAG: ${{ github.event.client_payload.ref }}
        run: echo mn2sts_VERSION=${mn2sts_TAG#*/v} >> ${GITHUB_ENV}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.prepare.outputs.default-ruby-version }}
          bundler-cache: true

      - run: rm -f bin/mn2sts.jar

      - run: bundle exec rake

      - run: |
          gem install gem-release
          gem bump --version ${mn2sts_VERSION} --no-commit

      - name: Push commit and tag
        run: |
          git add -u bin/mn2sts.jar lib/mn2sts/version.rb
          git commit -m "Bump version to ${mn2sts_VERSION}"
          git tag v${mn2sts_VERSION}
          git push github HEAD:${GITHUB_REF} --tags

      - if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        with:
          assignees: CAMOBAP
          update_existing: true
          search_existing: all
